############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

# [[main]]
# name = "Door Configurator"
# url = "https://doordesigner.inotherm-tuer.de/configurator/?partnerCode=48556"
# weight = 2

[[main]]
name = "Products"
url = "products/"
weight = 2
hasChildren = true

[[main]]
parent = "Products"
name= "Windows"
url = "products/windows"
weight = 1

[[main]]
parent = "Products"
name= "Doors"
url = "products/doors"
weight = 2

[[main]]
parent = "Products"
name= "Shutters"
url = "products/shutters"
weight = 3

[[main]]
parent = "Products"
name= "Canopies"
url = "products/canopies"
weight = 4

[[main]]
parent = "Products"
name= "Awnings"
url = "products/awnings"
weight = 5

[[main]]
parent = "Products"
name= "Mosquito Nets"
url = "products/mosquito-nets"
weight = 6

[[main]]
weight= 3
name= "Jobs Gallery"
url = "gallery"

# [[main]]
# weight = 4
# name = "VEKA Profiles"
# hasChildren = true

# [[main]]
# parent= "VEKA Profiles"
# name = "VEKA 82 MD"
# url= "82md/"

# [[main]]
# parent= "VEKA Profiles"
# name = "VEKA 82 AD"
# url= "82ad/"

# [[main]]
# parent= "VEKA Profiles"
# name = "VEKA 76 MD"
# url= "76md/"

# [[main]]
# parent= "VEKA Profiles"
# name = "VEKA 76 AD"
# url= "76ad/"

# [[main]]
# weight=5
# name= "Mosquito Nets"



# [[main]]
# parent = "Pages"
# name = "Blog"
# url = "blog/"

# [[main]]
# parent = "Pages"
# name = "Contact"
# url = "contact/"

# [[main]]
# parent = "Pages"
# name = "Authors"
# url = "authors/"

# [[main]]
# parent = "Pages"
# name = "Categories"
# url = "categories/"

# [[main]]
# parent = "Pages"
# name = "404 Page"
# url = "404/"


# footer menu
# [[footer]]
# name = "About"
# url = "about/"
# weight = 1

# [[footer]]
# name = "Elements"
# url = "elements/"
# weight = 2

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 3
